# Generated by Django 3.2.4 on 2021-07-01 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=30)),
                ('buxfer_account_id', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contra_account', models.CharField(blank=True, max_length=20, null=True)),
                ('contra_account_bank_code', models.CharField(blank=True, max_length=6, null=True)),
                ('constant_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('variable_code', models.CharField(blank=True, max_length=12, null=True)),
                ('user_identification', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_transaction_type', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_message', models.CharField(blank=True, max_length=200, null=True)),
                ('request_id', models.BigIntegerField(unique=True)),
                ('bank_transaction_id', models.BigIntegerField(unique=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction_account', to='fio.bankaccount')),
                ('contra_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction_contra_account', to='fio.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuxferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buxfer_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('account_id', models.BigIntegerField(blank=True, null=True)),
                ('account_name', models.CharField(blank=True, max_length=200, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True)),
                ('tag_names', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('is_future_dated', models.BooleanField(blank=True, null=True)),
                ('is_pending', models.BooleanField(blank=True, null=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buxfer_transaction_account', to='fio.bankaccount')),
                ('bank_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fio.transaction')),
                ('contra_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buxfer_transaction_contra_account', to='fio.bankaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio_bank_token', models.CharField(blank=True, max_length=100)),
                ('buxfer_username', models.CharField(blank=True, max_length=100)),
                ('buxfer_password', models.CharField(blank=True, max_length=100)),
                ('main_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fio.bankaccount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
