# Generated by Django 3.2.4 on 2021-06-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contra_account', models.CharField(blank=True, max_length=20, null=True)),
                ('contra_account_bank_code', models.CharField(blank=True, max_length=6, null=True)),
                ('constant_symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('variable_code', models.CharField(blank=True, max_length=12, null=True)),
                ('user_identification', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_transaction_type', models.CharField(blank=True, max_length=200, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(blank=True, max_length=20, null=True)),
                ('receiver_message', models.CharField(blank=True, max_length=200, null=True)),
                ('request_id', models.BigIntegerField(unique=True)),
                ('bank_transaction_id', models.BigIntegerField(unique=True)),
                ('comment', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
