# Generated by Django 3.2.5 on 2021-07-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buxfertransaction',
            old_name='contra_bank_account',
            new_name='to_account',
        ),
        migrations.RemoveField(
            model_name='buxfertransaction',
            name='bank_account',
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='from_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buxfer_transaction_account', to='fio.bankaccount'),
        ),
    ]
