# Generated by Django 3.2.4 on 2021-11-12 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buxfertransaction',
            name='buxfer_update_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
