# Generated by Django 3.2.4 on 2021-06-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0002_bankprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankprofile',
            name='fio_bank_token',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
