# Generated by Django 3.2.4 on 2021-11-13 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0002_buxfertransaction_buxfer_update_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('buxfer_transaction_sum', models.IntegerField()),
                ('bank_transaction_sum', models.IntegerField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fio.bankaccount')),
            ],
        ),
    ]
