# Generated by Django 3.2.5 on 2021-07-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0002_auto_20210703_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoTaggingString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagging_string', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
    ]
