# Generated by Django 3.2.4 on 2021-06-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0003_alter_bankprofile_fio_bank_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuxferTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='bankprofile',
            name='buxfer_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bankprofile',
            name='buxfer_username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
