# Generated by Django 3.2.4 on 2021-06-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0004_auto_20210626_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='buxfertransaction',
            name='account_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='bank_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fio.transaction'),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='buxfer_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='expense_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='is_future_dated',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='is_pending',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='tag_names',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='tags',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='buxfertransaction',
            name='transaction_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='buxfertransaction',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='buxfertransaction',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
