# Generated by Django 3.2.5 on 2021-07-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0005_buxfertransaction_raw_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='buxfertransaction',
            name='buxfer_bank_transaction_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
