# Generated by Django 3.2.5 on 2021-07-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0006_buxfertransaction_buxfer_bank_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='request_id',
            field=models.BigIntegerField(),
        ),
    ]
