# Generated by Django 3.2.5 on 2021-07-05 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0007_alter_transaction_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='cash',
            field=models.BooleanField(default=False),
        ),
    ]
