# Generated by Django 3.2.5 on 2021-07-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fio', '0009_auto_20210705_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='buxfer_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
